### ISSUE TITLE
XDMCP connection not closing on user logout

### ISSUE THREAD

**Issue by keeeeymann** [CanonicalLtd/lightdm#1]
I enabled XDMCP and it seems to work normally until I logout from remote desktop. The desktop session has fully exited, username has disappeared from the list, but it stuck at the wallpaper left on the screen unless I terminate the connection forcefully.
![snipaste_2017-12-10_01-51-23](https://user-images.githubusercontent.com/22412315/33798083-9427b2dc-dd4d-11e7-96eb-01955d04b246.png)

After I disconnect,  the greeter still considers me as logged in and marks me in bold.
lightdm.log at logout:

[+2744.81s] DEBUG: Seat (null): Exit status of /etc/X11/xdm/Xreset: 0
[+2744.81s] DEBUG: Seat (null): Stopping display server, no sessions require it
[+2744.81s] DEBUG: Seat (null): Display server stopped
[+2744.81s] DEBUG: Seat (null): Active display server stopped, starting greeter
[+2744.81s] DEBUG: Seat (null): Stopping; failed to start a greeter
[+2744.81s] DEBUG: Seat (null): Stopping
[+2744.81s] DEBUG: Seat (null): Stopped
[+2744.81s] WARNING: instance with invalid (NULL) class pointer
[+2744.81s] CRITICAL: g_signal_emit_valist: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

I confirmed this on many RHEL distributions, including CentOS 7, Fedora 27 and OpenSUSE Leap 42.3. But it's fine in Debian family.
LightDM versions are 1.25.0 on EPEL and 1.22.0 on OpenSUSE.

Full log:
[lightdm.log](https://github.com/CanonicalLtd/lightdm/files/1544939/lightdm.log)

**Comment by robert-ancell** [comment]
Thanks for the report! Just noting that I have seen this issue but not had the time to investigate it yet.

**Comment by robert-ancell** [comment]
Can you check if git master now works for you?

**Comment by robert-ancell** [comment]
Should be fixed in 1.25.1/1.24.1/1.18.4

**Comment by jasonshi-sw** [comment]
> Should be fixed in 1.25.1/1.24.1/1.18.4

where can i download the 1.25.1 rpm package for centos 7?
