### ISSUE TITLE
When will 1.25.2-0ubuntu1 be available in bionic?

### ISSUE THREAD

**Issue by rik-shaw** [CanonicalLtd/lightdm#10]
@robert-ancell I am hoping to test the fixes for the updated user background settings as discussed here: https://github.com/linuxmint/slick-greeter/issues/94

At this point I think I am still having issues with the service not being found that may be solved by 1.25.2:
```No such interface 'org.freedesktop.DisplayManager.AccountsService'```

I am not certain as to when 1.25.2-0ubuntu1 will make it to the bionic repos: are you able to help me understand when this will get to them? thanks...

**Comment by robert-ancell** [comment]
It's there now: https://launchpad.net/ubuntu/+source/lightdm/1.25.2-0ubuntu1

**Comment by rik-shaw** [comment]
Thanks for the quick work!  I can confirm everything is working well as long as the desktop is writing to 
/var/lib/AccountsService/users/<username> with the following entry:

[org.freedesktop.DisplayManager.AccountsService]
BackgroundFile='/path/to/file.png'

Since I am doubtful that all the various desktops will get this adjustment made for 18.04 but we want to stick with a lightdm greeter that shows the user desktop (slick-greeter seems like the best choice right now) I will use a lightdm login script to set the entry.  An ugly hack that means a changed desktop will not show until the *second time* logging in, but it will be acceptable while waiting for various desktops to catch up.

Thanks again for the help and great work!  We really need the features of lightdm such as remote login ability that gdm doesn't (yet?) provide.
