### ISSUE TITLE
Unity-greeter doesn't change background since 1.25.1 (Bionic)

### ISSUE THREAD

**Issue by khurshid-alam** [CanonicalLtd/lightdm#11]
On Bionic, Since lightdm 1.25.1 unity-greeter doesn't change background when user wallpapers is changed. From `/var/log/lightdm/seat0-greeter.log` couldn't find anything significant other than

`** (unity-settings-daemon:7310): WARNING **: 17:38:25.036: Unable to register client: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method 'RegisterClient'`

Downgrading lightdm to 1.25.0 fixes the issue.

All related components updated to latest versions.

**Comment by robert-ancell** [comment]
This is due to a change in the method we use to set/get the background in AccountsService. It requires the following change to land in unity-settings-daemon:
https://code.launchpad.net/~robert-ancell/unity-settings-daemon/accountsservice-background/+merge/335431

**Comment by khurshid-alam** [comment]
@robert-ancell 

I tried your patch. As per my testing it only changes the background for the main account (account created during installation).

However if I create accounts in u-c-c it doesn't change the account for those particular users.

1. Create a new user in u-c-c
2. Login and change the background
3. `dm-tool switch-to-greeter`

It doesn't chnage the background. In `/var/lib/AccountsService/users/,` the new accounts created by u-c-c doesn't have a BackgroundFile section under [org.freedesktop.DisplayManager.AccountsService] for example,


> [org.freedesktop.DisplayManager.AccountsService]
> BackgroundFile='/home/sunny/Pictures/horizon_wallpaper_by_nikusenpai-dbcrffq.jpg'

Manually adding it solves the issue.

**Comment by khurshid-alam** [comment]
Can you reproduce this?

I can't really find out why lightdm doesn't write BackgroundFile section in `/var/lib/AccountsService/users/` for new users created in u-c-c. Log doesn't show anything. Needs to go deeper. But I guess the problem isn't in accounts-service since this never went into upstream.

**Comment by robert-ancell** [comment]
LightDM doesn't write the data - it's always been the responsibility of u-c-c/u-s-d to do this. Did it ever write the value for new users? I suspect it only ever did it wen you change the background.

**Comment by khurshid-alam** [comment]
Yes it changes the background when I change the user bg. But it doesn't happen every time. From u-s-d log I find something like `No such method 'SetBackgroundFile'`. I suppose it happens when we try to set a bg with [old method](https://bazaar.launchpad.net/~robert-ancell/unity-settings-daemon/accountsservice-background/view/head:/plugins/background/gsd-background-manager.c#L456).

May be we should separate these into two functions. Try old one only if new-method fails.

```c
set_accountsservice_background (*) {
     /* code */
    return TRUE;
}

set_accountsservice_background_old (*) {
/*code*/
}

static void
picture_uri_changed (*) {
    if (!set_accountsservice_background (picture_path)) {
         set_accountsservice_background_old (picture_path);
    }
}
```
