### ISSUE TITLE
Suggest: strip the blank character in username text box

### ISSUE THREAD

**Issue by inpool** [CanonicalLtd/lightdm#14]
When I wake up the computer, generally using the space key, and lightdm back to capture the keystroke and the spaces will be automatically entered into the user name text box, lead to validate a pass-through, however, if the user name text box automatically before and after the blank character deletion, it will more convenient. Or if the input is not captured before the screen wakes up, it's okay to consider this suggestion.

**Comment by robert-ancell** [comment]
This behaviour is in the greeter - you will have to file a bug against the particular greeter you are using.

**Comment by charlesgoyard** [comment]
You can check an implementation in [this pull request for gtk-greeter](https://github.com/Xubuntu/lightdm-gtk-greeter/commit/59fb38ac8ccd66baadf5a32846d7addad425f51c).
