### ISSUE TITLE
Invalid test in configure.ac

### ISSUE THREAD

**Issue by ffauberteau** [CanonicalLtd/lightdm#15]
I'm updating LightDM for pkgsrc (NetBSD packager) and I encountered the following error:
=> Checking for portability problems in extracted files
ERROR: [check-portability.awk] => Found test ... == ...:
ERROR: [check-portability.awk] configure: if test "x$GCC" == xyes; then

Explanation:
===========================================================================
The "test" command, as well as the "[" command, are not required to know
the "==" operator. Only a few implementations like bash and some
versions of ksh support it.

The following patch fixes the error:
--- configure.ac.orig	2018-03-21 23:13:29.000000000 +0000
+++ configure.ac
@@ -15,12 +15,12 @@ AC_PROG_MKDIR_P
 AM_MAINTAINER_MODE
 
 dnl Check if the compiler really supports `-std=c99`.
-if test "x$ac_cv_prog_cc_c99" == xno; then
+if test "x$ac_cv_prog_cc_c99" = xno; then
     AC_MSG_ERROR([$CC does not support '-std=c99'.])
 fi
 
 dnl Enable compile warnings (only supporting GCC)
-if test "x$GCC" == xyes; then
+if test "x$GCC" = xyes; then
     WARN_CFLAGS="-Wall \
                  -Wstrict-prototypes \
                  -Wnested-externs \

**Comment by robert-ancell** [comment]
Fixed, thanks!
