### ISSUE TITLE
mouse cursor problem

### ISSUE THREAD

**Issue by melmelissa** [CanonicalLtd/lightdm#2]
Hello

is it possible to add an option to customize the mouse cursor for Lightdm ???

or if a trick exists, I am interested.
despite long research and some manipulations, it is still the Adwaita cursor that is present on Lightdm .....

I'm using Debian and ArchLinux with Cinnamon.
Thank you.

**Comment by robert-ancell** [comment]
The cursor is controlled by the greeter - LightDM doesn't render any graphics. You'll need to work out what greeter you are using and check that project.
