### ISSUE TITLE
extremely slow or impossible to use mouse with windows and desktop icons in VirtualBox guest

### ISSUE THREAD

**Issue by barsnick** [CanonicalLtd/lightdm#30]
Hi,
I originally reported this here:
https://bugzilla.redhat.com/show_bug.cgi?id=1600175
and was asked to upstream it with you.

With a recent update of lightdm, mouse control moving windows, accessing window controls, and also accessing desktop icons, has become non-responsive. Once in a while, the system reacts to the mouse again, only to become non-responsive again quite quickly.

Steps to Reproduce:
1. Boot into Fedora.
2. Launch default terminal from panel (tilix or mate-terminal) or any other program.
3. Try to move the window with the mouse, or resize it, or access its right-click menu items, or access desktop icons.

Actual results:
Window can't be moved with the mouse. Window can't be made fullscreen (double-click on title bar, or use of the respective title bar button). Can't copy/paste with the mouse. Can't access desktop icons (they don't even change their shade anymore when I hover the mouse over).

After a few minutes (?), most actions work again. Just for a short time though, then the whole desktop is stuck again. (See additional info below.)

This is all in Fedora (F27 and F28) VirtualBox guests, running on a Windows 10 host. 

Expected results:
Snappy reaction to mouse actions.

Additional info:
This is all in Fedora (F27 and F28) VirtualBox guests, running on a Windows 10 host. This happens both with and without VirtualBox's 3D acceleration support.

Interestingly, I can, most of the time, still fluidly control the icons and menus from/in the panel.

When stuck, I can't use right mouse actions (such as copy or paste) either, while pasting with Shift+Insert works.

As far as I could track it down, it happened with Fedora's update from lightdm-1.25.2-1 to 1.26.0-1. I am aware that your upstream code contains no changes between these versions. ;-) The latter Fedora package includes three patches from your upstream commits though:

https://github.com/CanonicalLtd/lightdm/commit/733d1758adc0003ebbdce31e6c6bb58b86816cbb
https://github.com/CanonicalLtd/lightdm/commit/9cfe924bb7bdfbb293686f2d636f461017f7c9dc
https://github.com/CanonicalLtd/lightdm/commit/149d9d7dff76f1db1daac33031f5d2d0c5407443

I have observed this behavior both on an F27 Cinnamon spin, and on an F28 Mate-Compiz spin. (These are special Fedora package compilations which concentrate on different desktops than the default Gnome3.) I tracked this down to lightdm, as that is the one obvious component both spins share, and it was a component which was updated just before the issue started occurring on each system. When I reverted this component to lightdm-1.25.2-1.fc28 (incl. lightdm-gobject), everything was fine again.

If you can't reproduce, I'd like a hint as to into which logs (or similar) I can look, whether I shall attach strace or something, or such. I'd like to avoid recompiling right now because it's a bit of a hassle, even though I consider myself good at it. ;-)

Thanks!

**Comment by barsnick** [comment]
It turns out that the downgrade of lightdm did not solve the issue. Possibly, the mate desktop is even running with marco, not lightdm (which is installed anyway, d'uh). So I'm closing this issue again.

**Comment by leigh123linux** [comment]
marco is a 'window manager'  (WM) which draws the window title and frame for apps within mate.

https://en.wikipedia.org/wiki/Window_manager

Lightdm is a 'display manager' (DM)  or login manager.

https://en.wikipedia.org/wiki/X_display_manager_(program_type)
