### ISSUE TITLE
make install fails on reinstall

### ISSUE THREAD

**Issue by Soapux** [CanonicalLtd/lightdm#35]
Doing subsequent make install fails with:

ln: failed to create symbolic link '/usr/share/accountsservice/interfaces/org.freedesktop.DisplayManager.AccountsService.xml': File exists

The install process tries to create the link with 'ln -s', so it fails since the symbolic link is already there.  Should the install use 'ln -sf'?

**Comment by robert-ancell** [comment]
Fixed in 0d3fda2a3d7077a89e1985908ebf5442ae7ef009, thanks!
