### ISSUE TITLE
lightdm-session should be installed as executable

### ISSUE THREAD

**Issue by paulmenzel** [CanonicalLtd/lightdm#37]
Instead of 644, shouldn’t `/usr/bin/lightdm-session` be made executable (755)?

**Comment by robert-ancell** [comment]
This file is not shipped as part of LightDM but provided in the packaging - which distribution are you using?

**Comment by paulmenzel** [comment]
Sorry, my bad. We built it ourselves, but I misread our build script.

    sed '/bin\/sh/ a \\n. /etc/profile' ${S}/tests/src/lightdm-session > ${D}/usr/bin/lightdm-session
    chmod 755 ${D}/usr/bin/lightdm-session

LightDM only has `tests/src/lightdm-session` with mode 770.
