### ISSUE TITLE
Allow different PAM configuration for Loging in and Unlocking an existing session

### ISSUE THREAD

**Issue by maxf130** [CanonicalLtd/lightdm#48]
I have configured my system to require both a password and a plugged in Yubikey in order to authenticate.  

It would be nice if I could configure lightdm in such a way that when unlocking an existing session, either one of the Yubikey or a password is sufficient in order to authenticate.  This will require an additional pam configuration file and associated configuration option, perhaps called pam-unlock-service.

As I type this I realise that this might be something for the locker to handle and not lightdm itself.  Does lightdm even know or care that a session is being unlocked or started?

Thanks

**Comment by robert-ancell** [comment]
This is probably best handled inside a PAM module - the module can check if the session is locked and have not require the password in this case.

The locking state is managed by logind - LightDM just monitors that service and prompts it when sessions should be locked / unlocked via greeters.
