### ISSUE TITLE
Default to "greeter-show-manual-login = true"

### ISSUE THREAD

**Issue by alkisg** [CanonicalLtd/lightdm#49]
Hi, since 2016 AccountsService uses a MAX_LOCAL_USERS=50 limit, meaning that only the first 50 users are able to login by default:
https://gitlab.freedesktop.org/accountsservice/accountsservice/issues/39

To match that change in AccountsService, please update the default lightdm configuration to:
`greeter-show-manual-login = true`

...so that at least the rest of the users are able to login by typing their username.

**Comment by robert-ancell** [comment]
We can't change the defaults as this would cause a system to change behaviour on upgrade. Those with larger systems will have to opt into this feature..

**Comment by alkisg** [comment]
Hi Robert, thank you for your answer, please allow me to add additional rationale on why this change is important, hoping I can convince you. I won't reopen the issue, let's keep it closed until/unless you change your mind. :)

1. Replying to "this would cause a system to change behavior on upgrade: UI changes happen frequently if there are important reasons to justify them, e.g. Ubuntu switched from gdm to lightdm and then back to gdm. I believe enabling all the users to log in is a great reason.

2. The other famous login managers do it by default:
GDM has a "Not listed?" button.
KDM has a "Different User" button.

3. It is required for LDAP logins, for NIS logins, and for other cases where accountsservice can't list the user but PAM does allow them to login.

4. Some lightdm-based distributions like debian configure their lightdm greeters to show a text box for the username, so they allow all users to login even with lightdm. Those won't get any changed behavior if greeter-show-manual-login defaults to true.
