### ISSUE TITLE
db-tool lock+x11vnc run cmd without unlock

### ISSUE THREAD

**Issue by Dimelay** [CanonicalLtd/lightdm#50]
Hi!
Im user xfce
Alt+r hot keys to xfce4-terminal (or any key to run any commands)

Step 1

on terminal
$ x11vnc

Step 2

$ dm-tool lock

Step 3

Connect to host via vnc
see black screen
Next press Alt+r and put any command
Command will be execute on new running terminal without unlock screen

Examples im put sudo reboot and my pc rebooted

**Comment by robert-ancell** [comment]
This sounds like an issue in XFCE - LightDM doesn't intercept keyboard events or draw anything to the screen.
