### ISSUE TITLE
Desktop cannot be connected until display of remote server connected.

### ISSUE THREAD

**Issue by Heermosi** [CanonicalLtd/lightdm#52]
I've detected this on computers equipped with Nvidia display cards.

OS System: Ubuntu Server 16.04 LTS
GPU: Nvidia GTX 1080Ti

The problem looks like this, if I startup the remote server without a display connected, the lightdm failed to start dues to no screen connect to it.
It was partly dues to gpumanager or xorg. so is there any solution to this?

**Comment by robert-ancell** [comment]
If you add the following to the LightDM configuration this should work:

```
[LightDM]
start-default-seat=false
```
