### ISSUE TITLE
Implement visual countdown when autologin-user-timeout is set

### ISSUE THREAD

**Issue by antimatter84** [CanonicalLtd/lightdm#53]
I have configured lightdm.conf with a 10 second autologin timeout. It works, but I don't see a countdown on the login screen. This would be a helpful feature reduce additional. MDM has this but sometimes distributions change the display manager and having a common set of useful features might be desirable. (E.g. one wouldn't have to switch to MDM to get that countdown back.)

**Comment by robert-ancell** [comment]
The greeter needs to implement this function, LightDM is just the service component. Please file against the greeter you are using.
