### ISSUE TITLE
Move website from freedesktop.org

### ISSUE THREAD

**Issue by fooishbar** [CanonicalLtd/lightdm#60]
Since the code for LightDM was never hosted on freedesktop.org, it would be good if LightDM could host its own website instead. We would of course be happy to set up any redirects as needed.

**Comment by fooishbar** [comment]
In addition, if the CLA does still apply (there are no docs stating that it does or doesn't), that would be a showstopper for us to continue hosting anything on fd.o. We do not host projects which require asymmetrical rights grants.

**Comment by robert-ancell** [comment]
The Wiki page is the closest thing we have to a website, and I'm happy to merge the content into the README.md and put a link to that in the old Wiki.

@fooishbar is the freedesktop.org position on CLAs documented anywhere? I've never heard of that specifically and can't seem to find any reference on the Wiki. The most appropriate page I could find was https://www.freedesktop.org/wiki/MissionStatement/ and that didn't mention anything other than the code should be under "free licenses".

**Comment by fooishbar** [comment]
Yeah, it's not mentioned since the mission statement is ancient and predates CLAs really being used. :\ It's a rule we've enforced for a long time though. After having written that I spent most of the weekend rewriting most of the wiki pages to document actual reality, including specifically CLAs, rewriting the license section away from an explicit preference for LGPL which is also massively out of step with our reality, etc.

**Comment by fooishbar** [comment]
Thanks btw!

**Comment by robert-ancell** [comment]
LightDM also predates CLAs being used :) It is currently covered by the Canonical CLA though.

I've updated the README.md and backed up the old Wiki pages. I'm having trouble finding my credentials for the Wiki site - are you able to delete those pages? We could set the Wiki page to point to https://github.com/CanonicalLtd/lightdm but I'm not too worried if not - I expect most people will just use a search engine to find the website.

The last piece of fd.org infrastructure we are using is the mailing list (https://lists.freedesktop.org/mailman/listinfo/lightdm). I assume this will be an issue? I'll need to discuss this on list for a replacement.

**Comment by fooishbar** [comment]
Thanks @robert-ancell! I'll finish up the mass update of the wiki now, update the primary links (e.g. on the main 'Software' page) to refer to GitHub, and put in redirects from the other pages as well.

Whilst you're the only project on the list of our projects with an asymmetrical corporate CLA, you're far from the only project who has moved off fd.o infrastructure for everything but the mailing list. So whilst it would be nice to move away from Mailman (and again, we're happy to do what we can to make that as smooth as possible), there's no big rush with it.

**Comment by robert-ancell** [comment]
[mailing list proposal to move from fd.org](https://lists.freedesktop.org/archives/lightdm/2019-February/001152.html)

**Comment by robert-ancell** [comment]
After much delay I have opened up a space on [discourse.ubuntu.com](https://discourse.ubuntu.com/c/light-dm/107) as a new home for LightDM. @fooishbar I had a look at the admin interface and I don't see how to close the mailing list - can you do that? It would be useful if the archives could be browsed online, but if not that's acceptable.

**Comment by fooishbar** [comment]
I've done it now in a way that keeps the archives. Thanks, & good luck!
