### ISSUE TITLE
Update launch and freedesktop pages with new project home?

### ISSUE THREAD

**Issue by AMDmi3** [CanonicalLtd/lightdm#7]
The project development seem to have moved to GitHub, however there's no mention of that on either

https://launchpad.net/lightdm
or
https://www.freedesktop.org/wiki/Software/LightDM/

People are confused because they don't see 1.25.1 release on LP and consider it a fake. Here, for example: https://repology.org/metapackage/lightdm/report

**Comment by robert-ancell** [comment]
Updated, thanks!
