### ISSUE TITLE
Ligthdm does not prompt for new password

### ISSUE THREAD

**Issue by mdhowle** [CanonicalLtd/lightdm#8]
When a user has an expired password and enters their login and password, they receive a message underneath the password text box reading "Changing password for \<user\>".    No new text boxes appear for the password and to verify the password.  The existing text box does not change the password.

The message changes whether using authenticating an LDAP user or a local user, but the issue is the same.

Attached [lightdm.log](https://github.com/CanonicalLtd/lightdm/files/1708441/lightdm.log)

#### Versions
Raspbian (Debian) 9.3 stretch

lightdm 1.18.3-1
lightdm-gtk-greeter 2.0.2-1

#### Steps to reproduce
1.  Expire a local user (chage -d 0 user)
2.  Attempt to login with user
3.  Receive the error message
4.  Type new password using existing text box.

**Comment by robert-ancell** [comment]
This sounds like an issue in lightdm-gtk-greeter - please file in https://bugs.launchpad.net/lightdm-gtk-greeter/+filebug
