### ISSUE TITLE
How to setup keyboard layout for lightdm?

### ISSUE THREAD

**Issue by navdeepio** [CanonicalLtd/lightdm#80]
I've tried everything

* configuring xorg.conf.d/00-keyboard.conf
* configuring .Xmodmap
* tweaking greeter settings

but have been unable to setup the dvorak keyboard layout with lightdm... is it a bug or is it not possible?

**Comment by robert-ancell** [comment]
LightDM doesn't set up the keyboard, this is either an X server configuration or greeter configuration option.
