### ISSUE TITLE
Memory leak; version 1.30.0

### ISSUE THREAD

**Issue by bronvic** [CanonicalLtd/lightdm#84]
My laptop was online for several days an I saw that almost all memory used and most of it because of lightdm

I'm Arch linux user. I'm using lightdm from my repo with standart pkgbuild: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/lightdm

Here is my htop
![2019-07-21-141740_5446x1300_scrot](https://user-images.githubusercontent.com/8941791/61590477-aca4d700-abc2-11e9-8576-5b823ea5fa70.png)

**Comment by robert-ancell** [comment]
The htop output shows that Xorg (the X server) is using all the memory, not LightDM.
