### ISSUE TITLE
Dynamic auto-login

### ISSUE THREAD

**Issue by dmonty2** [CanonicalLtd/lightdm#9]
How do I get lightdm to reload it's lightdm.conf on logout?

Just recently upgraded from Ubuntu 12.04 to 16.04 and we lost some lightdm functionality.

With 12.04 lightdm would reload it's lightdm.conf at log out.  This gave us the ability to dynamically change lightdm.conf to support auto-logins in our schools.

i.e. A teacher presses auto-login which updates the lightdm.conf to autologin-user=USERNAME.  Then reloads lightdm.service. This works great!

The problem is when the teacher want's auto-login disabled.  The login completes and lightdm.conf is changed back to remove "#autologin-user" but lightdm does not reload it's config settings.  It will autologin-user=USERNAME as it's stored in memory.  Previously at logout it would reload settings.  It seems I have to manually "systemctrl restart lightdm.service"

How do I get lightdm to reload it's lightdm.conf on logout?

Thanks.

**Comment by robert-ancell** [comment]
LightDM has never reloaded its configuration - perhaps something was restarting LightDM in 12.04 that made it look like it was?

There's been a long standing idea to move the autologin configuration to AccountsService - this would mean it would work without restarting LightDM.

It's unlikely a change like this would be released to 16.04 though.

**Comment by dmonty2** [comment]
Thanks.  I'll disable the dynamic Auto Login button feature for teachers.
You can close the ticket.
